const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "High quality cotton shirt",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Adidas",
      countInStock: 20,
      rating: 4.0,
      numReviews: 11,
      description: "High quality cotton shirt",
    },
    {
      _id: "3",
      name: "Nike Slim Chino",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 120,
      brand: "Nike",
      countInStock: 10,
      rating: 4.5,
      numReviews: 2,
      description: "High quality cotton shirt",
    },
    {
      _id: "4",
      name: "Puma Slim Shirt",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 120,
      brand: "Puma",
      countInStock: 6,
      rating: 4.5,
      numReviews: 10,
      description: "High quality cotton shirt",
    },
    {
      _id: "5",
      name: "Adidas Slim Jims",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "Adidas",
      countInStock: 10,
      rating: 4.5,
      numReviews: 5,
      description: "High quality cotton shirt",
    },
    {
      _id: "6",
      name: "Nike Blems",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 120,
      brand: "Adidas",
      countInStock: 15,
      numReviews: 12,
      description: "High quality cotton shirt",
    },
  ],
};

export default data;
